api_platform:
    title: Domain Watchdog API
    version: 1.0.0
    asset_package: 'api_platform'
    formats:
        jsonld: [ 'application/ld+json' ]
        xml: [ 'application/xml' ]
        json: [ 'application/json' ]
        text: [ 'text/calendar' ]
    docs_formats:
        jsonld: [ 'application/ld+json' ]
        jsonopenapi: [ 'application/vnd.openapi+json' ]
        html: [ 'text/html' ]
    defaults:
        stateless: true
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
        pagination_client_items_per_page: true
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    keep_legacy_inflector: false
    use_symfony_listeners: true
    show_webby: false
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    exception_to_status:
        # The 4 following handlers are registered by default, keep those lines to prevent unexpected side effects
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400 # Use a raw status code (recommended)
        ApiPlatform\Exception\InvalidArgumentException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
        ApiPlatform\ParameterValidator\Exception\ValidationExceptionInterface: 400
        Doctrine\ORM\OptimisticLockException: 409

        # Validation exception
        ApiPlatform\Validator\Exception\ValidationException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_UNPROCESSABLE_ENTITY

        App\Exception\DomainNotFoundException: 404
        App\Exception\MalformedDomainException: 403
        App\Exception\TldNotSupportedException: 403
        App\Exception\UnknownRdapServerException: 403
