framework:
    rate_limiter:
        authenticated_api:
            policy: 'sliding_window'
            limit: 25
            interval: '1 day'

        username_ip_login:
            policy: token_bucket
            limit: 5
            rate: { interval: '5 minutes' }

        ip_login:
            policy: sliding_window
            limit: 50
            interval: '15 minutes'

        user_register:
            policy: token_bucket
            limit: 5
            rate: { interval: '5 minutes' }

        rdap_requests:
            policy: sliding_window
            limit: 10
            interval: '1 hour'